# -*- coding: utf-8 -*-
"""aula_python_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muGoKMD9jPvGwtfsXSg7XPoGAYQ0kLrP

# Revisão

Definição de funções:
"""

def posicao(t, a, x0, v0):
  """Determina a posição de um objeto que descreve MRUV."""
  x = x0 + v0*t + a*t**2/2
  return x

"""Chamada da função:"""

pos = posicao(150., 1.5, 0., 35.)

print(pos)

"""Podemos criar funções com argumentos que possuem um valor padrão:

"""

def posicao(t, a, x0=0., v0=0.):
  """Determina a posição de um objeto que descreve MRUV."""
  x = x0 + v0*t + a*t**2/2
  return x

posicao(5., 1.,100)

"""Função anônima"""

f= lambda x: x**2

f(6)

"""Argumentos são valores que uma função recebe para
realizar suas operações.

Podemos passar argumentos para uma função de duas
maneiras: por posição ou por nome.

Argumentos tipo keyword são passados utilizando o nome
do parâmetro na chamada da função.
"""

def saudacao(name):
  print("Olá,", name)

saudacao(name = "João")

"""Em Python, podemos definir funções que recebem um
número arbitrário de argumentos utilizando o asterisco
(*).
"""

def listar_itens(*itens):
  for item in itens:
    print(item)

listar_itens("Maçã", "Banana", 'laranja')

"""# Módulos

Uma boa prática ao escrever códigos maiores é dividí-lo em arquivos menores, o que pode facilitar a manutenção.

Um módulo é um arquivo contendo definições e instruções Python. O nome do arquivo é o nome do módulo acrescido do sufixo .py.

Um módulo também pode ser muito útil para escrever funções que são usadas em vários programas diferentes. É preferível usar um arquivo separado para uma função do que copiá-la para dentro de vários programas.

Por exemplo, usando um editor de texto, foi criado um arquivo chamado fibonacci.py, contendo as funções fib e fib_lista, apresentadas na última aula. Ao importar um módulo, as funções definidas no arquivo são colocadas diretamente na tabelas de símbolos atual e poderão ser chamadas e executadas.

Podemos importar em um código funções que estão dentro de módulos das seguintes formas:

1.

```
import nome_modulo
```
e depois chamamos a função dentro do código
```
nome_modulo.nome_funcao()
```

2.
```
from nome_modulo import nome_funcao
```
e depois chamamos a função dentro do código
```
nome_funcao()
```
"""

import fibonacci

fibonacci.fib(50)

fibonacci.fib_lista(50)

"""Módulos podem importar outros módulos. É costume colocar todos os comandos de import no início do módulo ou de um programa.

Outras maneiras de importar as definições de um módulo são:
"""

from fibonacci import fib, fib_lista
fib(20)

import fibonacci as fibo
fibo.fib(10)

from fibonacci import fib_lista as f_l
f_l(30)

from fibonacci import *

"""**Atenção**

No último exemplo acima, importa todos os nomes definidos em um módulo usando o '*'. Isso nem sempre é aconselhado, pois introduz um conjunto desconhecido de nomes no ambiente, podendo levar a conflitos com outros nomes previamente definidos.

O Python guarda versões compiladas de cada módulo no diretório \__ pycache__ com o nome modulo.versão.pyc para acelerar o carregamento de módulos.

## Módulo Math

O módulo **math** contém todas as funções matemáticas padrão:

*   sqrt: raiz quadrada
*   pow: potência
*   exp : exponencial
*   log: logaritmo natural
*   log10: logaritmo (base 10)
*   sin: seno
*   cos: cosseno
*   tan: tangente
*   asin: arco seno
*   acos: arco cosseno
*   atan: arco tangente
*   cosh: cosseno hiperbólico
*   sinh: seno hiperbólico
*   tanh: tangente hiperbólica

entre outras.

**Atenção**:  ao usar **funções trigonométricas os ângulos devem estar em radianos** e não em graus.

Mais informações em https://docs.python.org/pt-br/3/library/math.html

A seguir mostramos várias maneiras de importar e usar as funções do módulo math
"""

from math import log,log10
x = log10(100)
print(x)

import math
y = math.log(4.)
print(y)

from math import pi
print(pi)

from math import exp
from math import sin, cos

from math import *

import math as mt
x = mt.tanh(10)
print(x)

# Algoritmo para converter a posição de um ponto dada em coordenadas polares (r,theta) para coordenadas
# Cartesianas (x,y)

from math import sin,cos,pi

r = float(input('Entre o valor de r: '))
d = float(input('Entre o valor de theta em graus: '))

theta = d*pi/180. #conversão de graus para radianos
x = r*cos(theta)
y = r*sin(theta)

print('x=', x, 'y=',y)

"""# Pacotes

São uma coleção de módulos organizados em diretórios para facilitar a organização e reutilização de códigos em projetos maiores.

Em Python, um pacote é um diretório contendo um arquivo \__ init__.py (pode ser um arquivo vazio), indicando que o diretório pode ser tratado como um pacote.

Nos referimos a um módulo dentro de um pacote como nomedopacote.nomedomodulo.


Um exemplo é o pacote Numpy, que tem vários módulos para cálculos numéricos. Veremos mais sobre este pacote nas próximas aulas.


Podemos importar pacotes das seguintes formas:
"""

#importando o pacote inteiro
import numpy
print(numpy.sqrt(16))  # chamando a função sqrt (raiz quadrada) do numpy

#importando o pacote com um alias ('apelido')
import numpy as np
print(np.sqrt(16))

#importando módulos dentro de pacotes
from numpy import random
print(random.rand(100))  # chamando a função rand do módulo random do numpy

#importando uma função específica de um módulo de um pacote
from numpy.random import randint
print(randint(1,100))

# alternativamente podemos fazer
import numpy as np
print(np.random.randint(1,10))

"""# Exercícios:



1. Crie uma função em Python para converter coordenadas cartesianas $(x,y)$ em coordenadas polares $(r,\theta)$.


(Fonte: https://www.geogebra.org/m/p8aRCfBU)

2. Escreva um programa para percorrer uma grid quadrada com x e y variando de 0 a 10 e o intervalo entre os pontos da grid igual a 1. Converta as coordenadas cartesianas de cada ponto $(x,y)$ desta grid para coordenadas polares, guardando os valores dos raios $r$ e dos ângulos $\theta$ (em graus) em duas listas separadas. Para cada ponto $(x,y)$ da grid também imprima em tela os valores $x,y,r,\theta$ correspondentes.
"""