# -*- coding: utf-8 -*-
"""aula_python_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jltuCMflqgmVsRcVKzfDPOuEGAneMRUt

# Funções

O Python já possui vários tipos de funções *built-in*, como print(), len(), range(), entre outras. Mas também é possível criar novas funções para executar alguma tarefa. As funções são muito úteis quando precisamos repetir alguma tarefa em diferentes partes do programa. Podemos colocar as instruções para realizar a tarefa em uma função e chamar a função quando for necessário. As funções também ajudam a organizar e modularizar os programas. Em Python as funções são definidas da seguinte forma:

    def nome_da_funcao(argumentos):
      comandos

Em Python, uma função é definida usando a palavra-chave def, seguida pelo nome da função e parênteses. Dentro dos parênteses são definidos os argumentos (parâmetros) que a função recebe como entrada (quando houver). O código que faz parte da função é indentado.
"""

def minha_funcao():
    print('Olá! Esta é a minha função!')

"""No exemplo acima a função minha_funcao não possui nenhum argumento. No corpo da função definimos os comandos que ela irá executar quando for chamada. Para chamar a função, basta fazer"""

minha_funcao()

"""No exemplo a seguir, definimos uma função com argumentos. Também introduzimos uma maneira de formatar a saída do print(). Veremos nas próximas aulas outras maneiras de formatar as saídas."""

def minha_funcao_com_argumentos(nome,saudacao):
    print(f'Olá, {nome}! Esta é a minha função! {saudacao}')

minha_funcao_com_argumentos('Fulana','Bem-vinda!')

"""Podemos também criar funções com argumentos que possuem um valor padrão:"""

def minha_funcao_com_argumentos_padrao(nome='Fulano',saudacao='Seja feliz!'):
    print(f'Olá, {nome}! Esta é a minha função! {saudacao}')

minha_funcao_com_argumentos_padrao('Cristina','Bem-vinda!')

minha_funcao_com_argumentos_padrao('Cristina') #aqui o segundo argumento não foi passado, então é usado o valor padrão dele

minha_funcao_com_argumentos_padrao() #aqui nenhum argumento foi passado, então os valores padrão são usados

"""Quando passamos argumentos na mesma ordem que os parâmetros, isso é chamado de argumento posicional. No exemplo acima

minha_funcao_com_argumentos_padrao('Cristina','Bem-vinda!')

os valores são passados como argumentos posicionais.

Na chamada de uma função também é possível usar argumentos nomeados, o que permite especificar qual valor corresponde a qual parâmetro, independentemente da ordem.
"""

minha_funcao_com_argumentos_padrao(saudacao ='Bem-vindo!',nome='Francisco')

"""Também é possível misturar argumentos posicionais e nomeados na mesma chamada, mas devemos garantir que os argumentos posicionais venham antes dos nomeados. Além disso, argumentos com valor padrão devem estar por último na definição da função."""

def exibir_info(produto, preco=100, quantidade=1):
    print(f"Produto: {produto}, Preço: {preco}, Quantidade: {quantidade}")

"""Na função acima, o argumento 'produto' é obrigatório e os outros argumentos são opcionais."""

# Chamada usando somente o argumento obrigatório (produto)
exibir_info("Camisa")  # Saída: Produto: Camisa, Preço: 100, Quantidade: 1

# Usando todos os argumentos posicionais
exibir_info("Calça", 150, 2)  # Saída: Produto: Calça, Preço: 150, Quantidade: 2

# Usando argumentos nomeados fora de ordem
exibir_info(quantidade=3, produto="Tênis", preco=200)  # Saída: Produto: Tênis, Preço: 200, Quantidade: 3

# Misturando argumentos posicionais e nomeados
exibir_info("Blusa", quantidade=4)  # Saída: Produto: Blusa, Preço: 100, Quantidade: 4

"""Já as seguintes formas de chamar a função verificação são inválidas:"""

exibir_info()

exibir_info(product='vestido')

exibir_info('televisão', produto='sofá')

"""Funções podem retornar um valor, utilizando o comando return"""

def reta(x,a,b):
  y = a*x+b

  return y

r = reta(10,3,2)  #armazena saída da função reta na variável r
print(r)

"""O comando return finaliza a execução da função e retorna o seu valor. return sem qualquer expressão como argumento
devolve None e se a função atinge o final e não há comando return, ela também devolve None.
Exemplo:
"""

print(minha_funcao())

"""Uma função para escrever sequência de Fibonacci até o número n:"""

def fib(n):
    """Imprime os números da sequência de Fibonacci ATÉ o número n.

     Isto é uma String de documentação (docstring).
     Algumas ferramentas de documentação utilizam as docstrings para produzir
     automaticamente a documentação online ou permitir que o usuário navegue
     mais facilmente pelo código.

     É uma boa prática de programação incluir sempre docstrings nas suas funções!! ;)

    """
    i, j = 0, 1
    while i < n:
        print(i, end=' ')  #O argumento end pode ser usado para evitar uma nova linha após a saída
        i,j = j,i+j
    return

print(fib)

help(fib)

fib(20)

fib(0)

print(fib(0))

"""Podemos escrever uma função que devolve uma lista de números da sequência de Fibonacci:"""

def fib_lista(n):
    """
    Função que retorna uma lista contendo os números da sequência de Fibonacci
    até o número n.
    """
    lista=[]
    i, j = 0, 1
    while i < n:
        lista.append(i)
        i,j = j,i+j

    return lista


f20 = fib_lista(20)
print(f20)

fib_lista(148)

"""**Funções anônimas**

Funções anônimas podem ser criadas com a palavra-chave lambda. As funções lambdas são restritas a uma única (em geral pequena) expressão.
"""

def quadrado(x):
    return x**2

f = quadrado(28)
print(f)

f2 = lambda x: x**2

f2(28)

f_soma = lambda a,b: a+b
f_soma(5,9)

def incrementar(n):
    return lambda x: x+n

f = incrementar(6)
f(21)

"""# Funções recursivas

A recursividade é um conceito em que uma função chama
a si mesma para resolver um problema.

É necessário ter um caso base para evitar chamadas
infinitas.
"""

def contador_regressivo(n):
  if n == 0:
    print("Fogo!")
  else:
    print(n)
    contador_regressivo(n - 1)


contador_regressivo(3)

"""# Escopo Local e Global

O escopo de uma variável determina onde ela pode ser
acessada dentro do programa.

• Variáveis definidas dentro de uma função têm escopo
local, ou seja, só podem ser acessadas dentro da função.

• Variáveis definidas fora de qualquer função têm escopo
global, podendo ser acessadas em qualquer parte do
programa
"""

a = 5.  # esta é uma variável global
b = 10.    # esta é outra variável global

def func(x):
  #global c
  c = 0.    # esta é uma variável local
  print('Dentro da função:')
  print('a=',a,' b=',b)
  print('c=',c)


print("Antes de iniciar: a=", a,'b=',b)

func(3)   # chamando a função func

print("Após a função:")
print('a=',a,' b=',b)    # a e b ainda existem, pois são globais
print('c=',c)            # Erro: c não existem mais

"""# Exercícios:


1. Em Python, peça para o usuário entrar com um valor de temperatura em Celsius, transforme para Fahrenheit e imprima o valor na tela. Use uma função em Python para realizar a conversão de temperaturas.


2. Crie uma função em Python para determinar os zeros da equação de segundo grau ax**2 + bx + c = 0. Não esqueça de levar em consideração as limitações e ambiguidades do algoritmo que fará este cálculo.

# Desafio: Criptografando texto

Implemente uma função chamada criptografar(texto, deslocamento) que recebe uma string (texto) e um número inteiro (deslocamento) e retorna o texto criptografado usando a Cifra de César.

Na Cifra de César, cada letra do texto é substituída por outra letra que está um certo número de posições à frente no alfabeto. Se passar do "z", volta para o "a".

Regras:

    1. Considere apenas letras minúsculas do alfabeto (a a z). As maiúsculas devem permanecer inalteradas.

    2. Caracteres que não são letras (como espaços, pontuação ou números) devem permanecer inalterados.

    3. O deslocamento pode ser positivo ou negativo.


**Dicas:** Você pode usar a função ord() para converter uma letra em número (ex: ord('a') = 97) e chr() para fazer o caminho inverso. Para 'dar a volta' no alfabeto use o operador %. Para testar se um caracter é uma letra (de a-z) use o método de strings .isalpha(). Para testar se uma letra é minúscula use o método de string .islower().
"""

