# -*- coding: utf-8 -*-
"""aula_python_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaUd1rWc3zYb4oYTiB0N9fxhoMpsRv0d

# Revisão
"""

import numpy as np

x = np.arange(0,2*np.pi,0.15)
f1 = np.sin(x)
f2 = np.cos(x)

print(x)
print(f1)

len(x)

"""# Matplotlib

O Matplotlib é um pacote que permite criar figuras estáticas, animadas e interativas em Python.

De acordo com https://matplotlib.org/: "Matplotlib makes easy things easy and hard things possible".

A maioria das funções para fazer gráficos simples encontram-se no módulo pyplot do Matplotlib. É muito comum fazer a importação desse módulo da seguinte forma:
"""

import matplotlib.pyplot as plt

"""Fazendo um gráfico de linha simples:"""

plt.plot(x,f1)  #gráfico com os valores da função seno (array f1) em função de x (array x) obtidos acima

plt.show()  #para mostrar o gráfico

"""Mesmo gráfico que o anterior só que mudando largura da linha e a cor da linha"""

plt.plot(x,f1, linewidth=1.0, color = 'green')
plt.show()

plt.plot(x,f1, '*--', color='cyan', lw=1, ms=10) # utilizando símbolo de estrela (*) e linha tracejada (--).
                                                     # lw -> largura da linha (Line Width)
                                                     # ms -> tamanho do símbolo (Marker Size)
plt.show()

"""**Exemplo 1: gráfico de linha simples**"""

plt.plot(x,f1,color ='red',marker='o',linestyle='--',linewidth=2.0,markersize=5,label='seno')  #gráfico com os valores da função seno (array f1) em função de x (array x) obtidos acima
plt.plot(x,f2,'bs-',label='cosseno') # adicionando na mesma figura o gráfico com os valores da função cosseno (array f2) em função de x (array x)
plt.xlabel('x ')  #nomeando eixo horizontal
plt.ylabel('f(x)')   #nomeando eixo vertical
plt.title('Funções seno e cosseno',fontsize=18)  #adicionando título
plt.legend() #para adicionar a legenda com as labels definidas acima na função plt.plot
plt.grid()  #adicionando grade
plt.xlim(0,1.5*np.pi)  #limites no eixo x
plt.ylim(-1.1,1.1)   #limites no eixo y

plt.show()  #para mostrar o gráfico

"""**Exemplo 2: scatter plot (gráfico de dispersão)**

Criando dois arrays, r1 e r2, contendo números aleatórios
"""

p1 = np.random.rand(50)  # array com 50 números aleatórios entre 0 e 4
p2 = np.random.rand(50)  # array com 50 números aleatórios entre 0 e 10

plt.scatter(p1,p2, marker='.', c = 'magenta')
plt.xlabel(r'$p_{1}$',fontsize=18)  #nomeando eixo horizontal usando comandos do latex e alterando o tamanho da fonte
plt.ylabel(r'$p_{2}$',fontsize=18) #nomeando eixo vertical
plt.show()

"""**Criando uma figura com vários gráficos (uma grid de subplots)**

"""

figura_grid = plt.figure(figsize=(15, 5))  #plt.figure cria um objeto figura; figsize altera o tamanho dessa figura

#primeiro subplot
plt.subplot(131)  #primeiro número indica 'linha' da grid, segundo a 'coluna' da grid e terceiro o número do subplot
plt.plot(x, f1, 'r-')
plt.xlabel('x')
plt.ylabel('sen(x)')
plt.title('Seno')

#segundo subplot
plt.subplot(132)
plt.scatter(p1, p2)
plt.xlabel(r'$p_{1}$')
plt.ylabel(r'$p_{2}$')

#terceiro subplot
plt.subplot(133)
plt.plot(x, x, marker='^', color='blue',linestyle='None', label='linear')
plt.plot(x, x**2, marker='d', color ='cyan', ls='--',label='quadrático')
plt.plot(x, x**3, 'm.', label='cúbico')
plt.legend(loc='upper left', fontsize=15)  # para adicionar a legenda; note que é possível escolher o local da legenda e o tamanho da fonte
plt.xlabel('x')
plt.ylabel('f(x)')

plt.suptitle('Título principal') #adiciona título da figura como um todo (e não de um subplot específico)

figura_grid.show()  #mostra o objeto figura_grid

"""O plt.figure cria um objeto figura. Esse objeto é como se fosse um espaço vazio onde podemos adicionar gráfico(s), usando as funções do Matplotlib.pyplot. Ao final, podemos salvar esse objeto figura como uma imagem em um arquivo (formato padrão é o png).


"""

figura_grid.savefig('figura_grid.png')

"""##Gráficos um pouco mais complexos

plt.subplots() é uma função do Matplotlib que retorna uma tupla contendo objetos figura e eixos. Quando usamos fig, ax = plt.subplots() estamos desempacotando esta tupla nas variáveis fig (objeto figura) e ax (objeto eixos).Tendo o objeto figura fig podemos mudar atributos no nível da figura e também salvar a figura como uma imagem depois. Tendo o objeto eixos ax podemos mudar atributos no nível dos eixos.
"""

fig, ax = plt.subplots(figsize=(6,4))
ax.plot(x, f1, '--', color='r', lw=1, ms=4)
ax.text(0.85, 0.7, 'texto aqui', transform=ax.transAxes) ## coordenadas relativas aos Axes da figura
                                                        ## esses vão de (0,0) no canto inferior esquerdo
                                                        ## a (1,1) no canto superior direito
                                                        ## Compare com próximo gráfico
ax.set_xlabel(r'$\alpha$')
ax.set_ylabel(r'$\sin(\alpha)$', fontsize=15)     ## Latex para gerar o texto das labels
plt.show()

fig, ax = plt.subplots(figsize=(6,4))
ax.plot(x, f1, 'o--', color='b', lw=0.6, ms=4)
ax.text(3., 0.75, 'texto aqui', transform=ax.transData)  ## coordenadas relativas aos dados da figura,
                                                        ## controlados por xlim e ylim
ax.set_xlabel(r'$\alpha$')
ax.set_ylabel(r'$\sin(\alpha)$', fontsize=15)
plt.show()

"""Múltiplos Axes em uma única figura (vários gráficos em uma mesma figura)"""

fig, axes = plt.subplots(2,2, figsize=(12,12))  #os dois primeiros argumentos indicam que serão 4 gráficos
                                                #em 2 linhas e 2 colunas
#primeiro gráfico
ax1 = axes[0][0]  #os índices [0][0] indicam que é o gráfico que ocupa primeira linha e primeira coluna da figura
ax1.plot(x, f1, 's-.', color='cyan', lw=0.4, ms=3)
ax1.text(0.5, 0.1, 'texto aqui', transform=ax.transAxes)
ax1.set_xlabel('x')
ax1.set_ylabel('sen(x)')

#segundo gráfico
ax2 = axes[0][1] #os índices [0][1] indicam que é o gráfico que ocupa primeira linha e segunda coluna da figura
ax2.plot(x, np.cos(x), '*-', color='k', lw=0.4, ms=3)
ax2.set_xlabel('x')
ax2.set_ylabel('cos(x)')

#terceiro gráfico
ax3 = axes[1][0]
ax3.scatter(p1,p2)
ax3.set_xlabel('p1')
ax3.set_ylabel('p2')

#quarto gráfico
ax4 = axes[1][1]
ax4.plot(x,x**3,'gs')
ax4.set_xlabel('x')
ax4.set_ylabel('f(x)')

fig.suptitle('Título de todos os plots', fontsize=20)
fig.show()

"""## Atividade:

Faça gráficos das posições, velocidades e aceleração obtidas em função do tempo na atividade da última aula e coloque os três gráficos em uma mesma figura um embaixo do outro. Salve a figura em pdf.

"""